# filetypes.saif.conf - تعريف لغة سيف

[settings]
extension=سيف

# الكلمات المفتاحية
keywords=اذا والا طالما لكل افعل عدد محرف كسري مزدوج عدم ارجع أرجع توقف استمر هيكل اتحاد تعداد تعريف_نوع ثابت ثابت_داخلي خارجي غير_موقع موقع صحيح خطأ نجاح فشل فارغ حجم عنوان مرجع تفرع حالة افتراضي ادرج عرف

# المكتبات
keywords2=كرتونة.ع بصمة.ع خط.ع صوت.ع ملفات.ع نصوص.ع نظام.ع مرشد.ع

# الدوال المدمجة
keywords3=اكتب اكتب_سطر اقرأ اقرأ_محرف افتتح اغلق احجز حرر انسخ_نص ادمج_نص طول_نص قارن_نص بحث_نص

[styling]
keyword=0x0000FF
keyword2=0x008000
keyword3=0xFF8000
string=0xFF00FF
comment=0x808080
number=0x00A0A0

[build-menu]
FT_00_LB=_ترجمة
FT_00_CM=/home/siso/saif-editor/saif-lang/حداد2 %f
FT_00_WD=%d

FT_01_LB=_تشغيل
FT_01_CM=/home/siso/saif-editor/saif-lang/حداد2 %f && ./%e
FT_01_WD=%d

FT_02_LB=_ترجمة وتشغيل
FT_02_CM=/home/siso/saif-editor/saif-lang/حداد2 %f && ./%e
FT_02_WD=%d
